train:
  number_of_problems_per_batch: 8
  per_device_train_batch_size: 8
  num_samples_per_problem: 4

  learning_rate: 5e-7
  beta: 0.001
  mu: 2

  reward_list: ["accuracy", "pedagogical_alignment", "think"]
  reward_weights: [0.45, 0.45, 0.1]

  top_k_adv: null # If specified, use top-k advantage sampling per problem during training for each device. (If 2 device, sample top_k_adv*2 samples)
  normalize_tree_advantages: true

teacher_model:
  model_name_or_path: Qwen/Qwen2.5-3B-Instruct
  lora:
    enable: true
    rank: 64
    alpha: 64
  vllm:
    temperature: 1.0
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.4
    number_of_gpus_per_instance: 1
    max_number_of_instances: -1
    load_and_unload: true
    use_v0: true
    enforce_eager: true

student_model:
  model_name_or_path: neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.4
    number_of_gpus_per_instance: 1
    max_number_of_instances: -1
    use_v0: true

    load_and_unload: true
    enforce_eager: true

judge_model:
  model_name_or_path: Qwen/Qwen2.5-14B-Instruct-AWQ
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.4
    number_of_gpus_per_instance: 1
    max_number_of_instances: -1
    load_and_unload: true
    use_awq: true
    use_v0: true
    enforce_eager: true

reward_model:
  model_name_or_path: Answer # If we set this to None we get the -r_sol run.

huggingface:
  name: <huggingface_name>
  push_to_hub: false

logging:
  wandb: true
  wandb_project: train-rl-SPO_LAB
  wandb_run_name: Qwen2.5-3B-Instruct(LoRA_64)_3R_NormalizedAdv_5
  run_group: 3b
  wandb_tags: ["3b"]
  save_dir: checkpoints/3b_3R_NormalizedAdv_5
  save_steps: 10


generation:

  max_turns: 15
  max_group_size: 3
  branch_size: 3

  # This turns on thinking.
  use_thinking: true
  force_thinking: true
  convert_think_to_turn_reward: true

  # This turns on the hard lambda.
  pedgagogical_advantage_lambda: 0.5
  use_soft_pedagogical_reward: true # If we set this to true we calculate each rewards following the pedagogical rule independently.
  ignore_rejected_judge: true # If we set this to true we get the soft lambda runs. (If you use soft pedagogical reward, set this to true)

  use_experimental_shared_memory: false

  number_judge_attempts: 2

  # If we turn this on we get the lambda=0.0 run
  # number_judge_attempts: 0
  # judges_rules_prompts_paths: {}

dataset:
  max_train_examples: 2000
  lower_bound_solve_rate: 0.2