teacher_model:
  model_name_or_path: models/ConstructivistRL-7b_Soft1.0
  use_openrouter: false
  vllm:
    temperature: 1.0
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.4
    number_of_gpus_per_instance: 1
    load_and_unload: true
    
student_model:
  model_name_or_path: neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.4
    number_of_gpus_per_instance: 1
    load_and_unload: true

judge_model:
  model_name_or_path: Qwen/Qwen2.5-14B-Instruct-AWQ
  vllm:
    use_awq: true
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.5
    number_of_gpus_per_instance: 1
    load_and_unload: false

reward_model:
  model_name_or_path: "Answer"

logging:
  wandb: true
  wandb_project: eval
  wandb_run_name: ConstructivistRL-7B_Soft1.0_2
  run_group: tutor
  wandb_tags: ["tutor", "7b"]
