teacher_model:
  model_name_or_path: models/ConstructivistRL-GDPO-7b_Soft1.0_Think
  use_openrouter: false
  vllm:
    temperature: 1.0
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.5
    number_of_gpus_per_instance: 2
    use_v0: true
    
student_model:
  model_name_or_path: neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.5
    number_of_gpus_per_instance: 2
    use_v0: true

judge_model:
  model_name_or_path: Qwen/Qwen2.5-14B-Instruct-AWQ
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.5
    number_of_gpus_per_instance: 2
    use_v0: true

reward_model:
  model_name_or_path: "Answer"

logging:
  wandb: true
  wandb_project: eval_GDPO
  wandb_run_name: ConstructivistRL(GDPO)-7b_Soft1.0(Think)
  run_group: tutor
  wandb_tags: ["tutor", "7b"]

generation:
  use_thinking: true
  force_thinking: true